# Nightfox colors for Swaylock
## name: terafox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/terafox/swaylock.conf

# Background
color=0f1c1e

# Inside (typing/verifying/wrong)
inside-color=152528
inside-clear-color=152528
inside-ver-color=152528
inside-wrong-color=152528

# Ring
ring-color=254147
ring-clear-color=fda47f
ring-ver-color=4d7d90
ring-wrong-color=e85c51

# Key highlight
key-hl-color=ad5c7c
bs-hl-color=e85c51

# Separator
separator-color=152528

# Text
text-color=e6eaea
text-clear-color=e6eaea
text-ver-color=e6eaea
text-wrong-color=e6eaea

# Layout text
layout-text-color=587b7b
