# Nightfox colors for Swaylock
## name: nightfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/swaylock.conf

# Background
color=131a24

# Inside (typing/verifying/wrong)
inside-color=192330
inside-clear-color=192330
inside-ver-color=192330
inside-wrong-color=192330

# Ring
ring-color=29394f
ring-clear-color=dbc074
ring-ver-color=6085b6
ring-wrong-color=c94f6d

# Key highlight
key-hl-color=9d79d6
bs-hl-color=c94f6d

# Separator
separator-color=192330

# Text
text-color=cdcecf
text-clear-color=cdcecf
text-ver-color=cdcecf
text-wrong-color=cdcecf

# Layout text
layout-text-color=71839b
