# Nightfox colors for Swaylock
## name: dawnfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/dawnfox/swaylock.conf

# Background
color=ebe5df

# Inside (typing/verifying/wrong)
inside-color=faf4ed
inside-clear-color=faf4ed
inside-ver-color=faf4ed
inside-wrong-color=faf4ed

# Ring
ring-color=ebdfe4
ring-clear-color=ea9d34
ring-ver-color=295e73
ring-wrong-color=b4637a

# Key highlight
key-hl-color=907aa9
bs-hl-color=b4637a

# Separator
separator-color=faf4ed

# Text
text-color=575279
text-clear-color=575279
text-ver-color=575279
text-wrong-color=575279

# Layout text
layout-text-color=a8a3b3
