# Nightfox colors for Swaylock
## name: dayfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/dayfox/swaylock.conf

# Background
color=e4dcd4

# Inside (typing/verifying/wrong)
inside-color=f6f2ee
inside-clear-color=f6f2ee
inside-ver-color=f6f2ee
inside-wrong-color=f6f2ee

# Ring
ring-color=d3c7bb
ring-clear-color=ac5402
ring-ver-color=223d90
ring-wrong-color=a5222f

# Key highlight
key-hl-color=6e33ce
bs-hl-color=a5222f

# Separator
separator-color=f6f2ee

# Text
text-color=3d2b5a
text-clear-color=3d2b5a
text-ver-color=3d2b5a
text-wrong-color=3d2b5a

# Layout text
layout-text-color=824d5b
