# Nightfox colors for Swaylock
## name: nordfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nordfox/swaylock.conf

# Background
color=232831

# Inside (typing/verifying/wrong)
inside-color=2e3440
inside-clear-color=2e3440
inside-ver-color=2e3440
inside-wrong-color=2e3440

# Ring
ring-color=444c5e
ring-clear-color=ebcb8b
ring-ver-color=668aab
ring-wrong-color=bf616a

# Key highlight
key-hl-color=b48ead
bs-hl-color=bf616a

# Separator
separator-color=2e3440

# Text
text-color=cdcecf
text-clear-color=cdcecf
text-ver-color=cdcecf
text-wrong-color=cdcecf

# Layout text
layout-text-color=7e8188
